/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_myrddin_triangulate_Triangulate */

#ifndef _Included_fr_myrddin_triangulate_Triangulate
#define _Included_fr_myrddin_triangulate_Triangulate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_myrddin_triangulate_Triangulate
 * Method:    jniTriangulate
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_fr_myrddin_triangulate_Triangulate_jniTriangulate
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
